// =============================================================================
// EXISTING TYPES — preserved exactly for backward compatibility
// =============================================================================

export type ProcessingMode = "fast" | "advanced";

export type OutputFormat = "jpeg" | "png" | "webp";

export interface ResizeOptions {
  width?: number;
  height?: number;
  maintainAspectRatio: boolean;
}

export interface ProcessingOptions {
  mode: ProcessingMode;
  format: OutputFormat;
  quality: number;        // 80-100
  microCrop: number;      // 0-5 px
  colorShift: number;     // -1 to +1 percent
  noiseInjection: number; // 0 to 1 percent
  globalResize: ResizeOptions;
}

export type FileStatus = "queued" | "processing" | "done" | "error";

export interface MetadataField {
  key: string;
  value: string;
  category: "camera" | "location" | "ai" | "software" | "other";
  stripped: boolean;
}

export interface CropData {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ImageFile {
  id: string;
  file: File;
  mediaType: MediaType;
  preview: string;
  status: FileStatus;
  progress: number;
  processedBlob: Blob | null;
  processedPreview: string | null;
  metadataBefore: MetadataField[];
  metadataAfter: MetadataField[];
  error?: string;
  cropData?: CropData;
  customResize?: ResizeOptions;
  customName?: string;
}

// =============================================================================
// SPRINT 01 — Processing Architecture
// New unified types for image / video / audio support
// =============================================================================

// ─── Media type discriminator ─────────────────────────────────────────────────

export type MediaType = "image" | "video" | "audio";

// ─── Privacy / branding mode (Sprint 10) ─────────────────────────────────────
//
// Mode A — Privacy Clean:  remove all identifying metadata, inject nothing.
// Mode B — Clean+Branding: remove identifying metadata, inject mrashed21 tags.

export type PrivacyMode = "privacy-clean" | "clean-branding";

// ─── Branding fields injected in Mode B (Sprint 10) ──────────────────────────

export interface BrandingConfig {
  creator: string;   // "Muhammad Rashed"
  author: string;    // "Muhammad Rashed"
  software: string;  // "mrashed21 Media Processor"
  keywords: string[]; // ["mrashed21", "muhammad rashed"]
}

// ─── Metadata removal statistics per file ────────────────────────────────────

export interface MetadataStats {
  fieldsFound: number;
  fieldsRemoved: number;
  originalSize: number;   // bytes
  processedSize: number;  // bytes
  savedBytes: number;     // originalSize - processedSize
  savedPercent: number;   // 0-100
}

// ─── Per-file processing result ───────────────────────────────────────────────

export interface ProcessingResult {
  blob: Blob;
  mimeType: string;
  filename: string;        // generated by filename engine (Sprint 11)
  metadataAfter: MetadataField[];
  stats: MetadataStats;
}

// ─── Unified media file (Sprint 04+) ─────────────────────────────────────────
//
// Used by the universal upload system. Replaces ImageFile for new queue UI.
// ImageFile is kept for the current image-only components.

export interface MediaFile {
  id: string;
  file: File;
  mediaType: MediaType;
  preview: string | null;   // Object URL; null for audio-only files
  status: FileStatus;
  progress: number;         // 0–100
  result: ProcessingResult | null;
  metadataBefore: MetadataField[];
  error?: string;
  // Image-specific (optional for non-image files)
  cropData?: CropData;
  customResize?: ResizeOptions;
  customName?: string;
}

// ─── Image processing options (extended, Sprint 06+) ─────────────────────────

export interface ImageProcessingOptions {
  removeExif: boolean;
  removeGps: boolean;
  removeIptc: boolean;
  removeXmp: boolean;
  preserveOrientation: boolean;
  preserveDimensions: boolean;    // MUST NOT downscale unless user requests
  outputFormat: OutputFormat;
  outputQuality: number;          // 80–100; no silent lossy compression
  // Optional: micro-adjustments for watermark disruption
  microCrop: number;              // 0–5 px
  colorShift: number;             // -1 to +1 percent
  noiseInjection: number;         // 0 to 1 percent
}

// ─── Video processing options (Sprint 08) ────────────────────────────────────

export interface VideoProcessingOptions {
  removeMetadata: boolean;
  preserveResolution: boolean;
  preserveAudio: boolean;
  // Remux (stream-copy) is always preferred over re-encode
  // Re-encode only happens when metadata cannot be removed via remux
  forceReencode: boolean;
}

// ─── Audio processing options (Sprint 09) ────────────────────────────────────

export interface AudioProcessingOptions {
  removeId3Tags: boolean;
  removeArtist: boolean;
  removeAlbum: boolean;
  removeTitle: boolean;
  removeComment: boolean;
  removeEncoder: boolean;
  preserveAudioQuality: boolean;
}

// ─── Video metadata (Sprint 08) ───────────────────────────────────────────────

export interface VideoMetadata {
  duration?: number;    // seconds
  width?: number;       // px
  height?: number;      // px
  fps?: number;
  videoCodec?: string;
  audioCodec?: string;
  hasAudio: boolean;
  bitrate?: number;     // kbps
}

// ─── Audio metadata (Sprint 09) ───────────────────────────────────────────────

export interface AudioMetadata {
  duration?: number;    // seconds
  bitrate?: number;     // kbps
  sampleRate?: number;  // Hz
  channels?: number;
  codec?: string;
  tags?: Record<string, string>; // ID3 / vorbis comment fields
}

// ─── Supported MIME types registry ───────────────────────────────────────────

export interface SupportedMimeType {
  mime: string;
  mediaType: MediaType;
  extensions: string[];
  label: string;
}

// ─── Processing error types ───────────────────────────────────────────────────

export type ProcessingErrorCode =
  | "UNSUPPORTED_FILE"
  | "FILE_TOO_LARGE"
  | "EMPTY_FILE"
  | "CORRUPTED_FILE"
  | "PROCESSING_FAILED"
  | "CANCELLED"
  | "NETWORK_ERROR"
  | "UNKNOWN";

export interface ProcessingError {
  code: ProcessingErrorCode;
  message: string;       // user-friendly message
  technical?: string;    // raw error for debugging (never shown to user)
}
